"""
Run the full study: every instrument at the theory-default parameters, plus a
parameter-sensitivity grid, and write all artifacts + a SUMMARY.md.

    python3 src/run_all.py
"""
from __future__ import annotations

import json
import os
from dataclasses import asdict

import pandas as pd

from data_loader import load
from strategy import SMCStrategy, Params
from backtest import trades_to_frame, metrics
from plot_svg import write_equity_svg
import sensitivity

HERE = os.path.dirname(__file__)
RESULTS = os.path.join(HERE, "..", "results")

# (file, name, killzone, notes)
INSTRUMENTS = [
    ("EURUSD_D1.csv", "EURUSD_D1", False, "Forex — EUR/USD daily, 2007-2020 (14y)"),
    ("EURUSD_H1.csv", "EURUSD_H1", True,  "Forex — EUR/USD 1h intraday, 6 months (killzone-gated)"),
    ("NIFTY_D1.csv",  "NIFTY_D1",  False, "Indian index — NIFTY 50 daily, 2021-2026"),
]


def run_one(fname, name, killzone, notes):
    path = os.path.join(HERE, "..", "data", fname)
    df = load(path)
    p = Params(use_killzone=killzone)  # theory defaults (n_major=5, min_rr=3, poi=fvg)
    trades = SMCStrategy(df, p).run()
    tf = trades_to_frame(trades)
    m, curve = metrics(trades)
    m.update(dataset=name, notes=notes, bars=len(df),
             period=f"{df.timestamp.iloc[0].date()} -> {df.timestamp.iloc[-1].date()}",
             params=asdict(p))

    tf.to_csv(os.path.join(RESULTS, f"{name}_trades.csv"), index=False)
    with open(os.path.join(RESULTS, f"{name}_metrics.json"), "w") as fh:
        json.dump(m, fh, indent=2, default=str)
    pd.DataFrame({"equity": curve}).to_csv(os.path.join(RESULTS, f"{name}_equity.csv"), index=False)
    write_equity_svg(curve, f"{name} equity (1% risk/trade)  return={m.get('return_pct','?')}%",
                     os.path.join(RESULTS, f"{name}_equity.svg"))
    return m


def fmt(m, keys):
    return {k: m.get(k) for k in keys}


def main():
    os.makedirs(RESULTS, exist_ok=True)
    summaries = []
    for fname, name, kz, notes in INSTRUMENTS:
        m = run_one(fname, name, kz, notes)
        summaries.append(m)
        print(f"{name:11s} n={m.get('trades'):>3} WR={m.get('win_rate_pct')}% "
              f"avgR={m.get('avg_R')} PF={m.get('profit_factor')} ret={m.get('return_pct')}%")

    # sensitivity grids
    sens = {}
    for fname, name, kz, _ in INSTRUMENTS:
        sens[name] = sensitivity.run(os.path.join(HERE, "..", "data", fname), name, kz)

    _write_summary(summaries, sens)
    print(f"\nArtifacts written to {os.path.abspath(RESULTS)}")


def _write_summary(summaries, sens):
    lines = ["# SMC Backtest — Results Summary\n",
             "_Generated by `src/run_all.py`. All trades use the theory-default "
             "parameters (fractal N=5 major / 2 internal, displacement body≥1×ATR or "
             "≥60% body, FVG 50% entry, SL beyond the swept wick, TP = nearest major "
             "liquidity pool at ≥3R, longs in discount / shorts in premium)._\n",
             "## Headline (default parameters)\n",
             "| Instrument | Trades | Win% | Avg R | Profit Factor | Max DD % | Return % (1% risk) |",
             "|---|--:|--:|--:|--:|--:|--:|"]
    for m in summaries:
        lines.append(
            f"| {m['dataset']} ({m['notes']}) | {m.get('trades')} | {m.get('win_rate_pct')} | "
            f"{m.get('avg_R')} | {m.get('profit_factor')} | {m.get('max_drawdown_pct')} | "
            f"{m.get('return_pct')} |")

    lines.append("\n## Parameter sensitivity (is the edge stable?)\n")
    for name, rows in sens.items():
        lines.append(f"### {name}\n")
        lines.append("| n_major | min_rr | poi | trades | win% | avg R | PF | total R |")
        lines.append("|--:|--:|--|--:|--:|--:|--:|--:|")
        for r in rows:
            lines.append(f"| {r['n_major']} | {r['min_rr']} | {r['poi']} | {r['trades']} | "
                         f"{r.get('win_rate_pct')} | {r.get('avg_R')} | "
                         f"{r.get('profit_factor')} | {r.get('total_R')} |")
        lines.append("")
    with open(os.path.join(RESULTS, "SUMMARY.md"), "w") as fh:
        fh.write("\n".join(lines))


if __name__ == "__main__":
    main()
